// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmiYbguRvaHUKIzZd5iedwZ6SL_kxSUGk',
    appId: '1:1085563366963:web:04f92d2120ef1599103d46',
    messagingSenderId: '1085563366963',
    projectId: 'testbankup',
    authDomain: 'testbankup.firebaseapp.com',
    storageBucket: 'testbankup.appspot.com',
    measurementId: 'G-BJL6ZDBD53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhhYYI0A9SNUSLfGeuB44Zzwc3PbDaMLg',
    appId: '1:1085563366963:android:148dfd0c4405b934103d46',
    messagingSenderId: '1085563366963',
    projectId: 'testbankup',
    storageBucket: 'testbankup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlzsZbOnqKZij4HHRA-44-YH5pcx43_L8',
    appId: '1:1085563366963:ios:aede78f82e290b58103d46',
    messagingSenderId: '1085563366963',
    projectId: 'testbankup',
    storageBucket: 'testbankup.appspot.com',
    androidClientId: '1085563366963-nd2647qk5s2aqo7qlb1sk595aq05aqdg.apps.googleusercontent.com',
    iosClientId: '1085563366963-24i9oq9tsqoasu7rsl1ir8i6hi77tqe2.apps.googleusercontent.com',
    iosBundleId: 'com.swiftsol.bankup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlzsZbOnqKZij4HHRA-44-YH5pcx43_L8',
    appId: '1:1085563366963:ios:dc62ebd59684a8d3103d46',
    messagingSenderId: '1085563366963',
    projectId: 'testbankup',
    storageBucket: 'testbankup.appspot.com',
    androidClientId: '1085563366963-nd2647qk5s2aqo7qlb1sk595aq05aqdg.apps.googleusercontent.com',
    iosClientId: '1085563366963-vrp12cmaagrt15b4di09c63c3e6av3ln.apps.googleusercontent.com',
    iosBundleId: 'com.swiftsol.bankup.RunnerTests',
  );
}
